// config.js — Vestibulinho ETEC 2026
// Gerado automaticamente. 244 dias de estudo.

const CRONOGRAMA = [
  {
    "date": "01/04/2026",
    "file": "01_04_2026",
    "day": "quarta",
    "week": 14,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "02/04/2026",
    "file": "02_04_2026",
    "day": "quinta",
    "week": 14,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "03/04/2026",
    "file": "03_04_2026",
    "day": "sexta",
    "week": 14,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "04/04/2026",
    "file": "04_04_2026",
    "day": "sabado",
    "week": 14,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "05/04/2026",
    "file": "05_04_2026",
    "day": "domingo",
    "week": 14,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "06/04/2026",
    "file": "06_04_2026",
    "day": "segunda",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "07/04/2026",
    "file": "07_04_2026",
    "day": "terca",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "08/04/2026",
    "file": "08_04_2026",
    "day": "quarta",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "09/04/2026",
    "file": "09_04_2026",
    "day": "quinta",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "10/04/2026",
    "file": "10_04_2026",
    "day": "sexta",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "11/04/2026",
    "file": "11_04_2026",
    "day": "sabado",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "12/04/2026",
    "file": "12_04_2026",
    "day": "domingo",
    "week": 15,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "13/04/2026",
    "file": "13_04_2026",
    "day": "segunda",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "14/04/2026",
    "file": "14_04_2026",
    "day": "terca",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "15/04/2026",
    "file": "15_04_2026",
    "day": "quarta",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "16/04/2026",
    "file": "16_04_2026",
    "day": "quinta",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "17/04/2026",
    "file": "17_04_2026",
    "day": "sexta",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "18/04/2026",
    "file": "18_04_2026",
    "day": "sabado",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "19/04/2026",
    "file": "19_04_2026",
    "day": "domingo",
    "week": 16,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "20/04/2026",
    "file": "20_04_2026",
    "day": "segunda",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "21/04/2026",
    "file": "21_04_2026",
    "day": "terca",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "22/04/2026",
    "file": "22_04_2026",
    "day": "quarta",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "23/04/2026",
    "file": "23_04_2026",
    "day": "quinta",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "24/04/2026",
    "file": "24_04_2026",
    "day": "sexta",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "25/04/2026",
    "file": "25_04_2026",
    "day": "sabado",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "26/04/2026",
    "file": "26_04_2026",
    "day": "domingo",
    "week": 17,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "27/04/2026",
    "file": "27_04_2026",
    "day": "segunda",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "28/04/2026",
    "file": "28_04_2026",
    "day": "terca",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "29/04/2026",
    "file": "29_04_2026",
    "day": "quarta",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "30/04/2026",
    "file": "30_04_2026",
    "day": "quinta",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "01/05/2026",
    "file": "01_05_2026",
    "day": "sexta",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "02/05/2026",
    "file": "02_05_2026",
    "day": "sabado",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "03/05/2026",
    "file": "03_05_2026",
    "day": "domingo",
    "week": 18,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "04/05/2026",
    "file": "04_05_2026",
    "day": "segunda",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "05/05/2026",
    "file": "05_05_2026",
    "day": "terca",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "06/05/2026",
    "file": "06_05_2026",
    "day": "quarta",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "07/05/2026",
    "file": "07_05_2026",
    "day": "quinta",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "08/05/2026",
    "file": "08_05_2026",
    "day": "sexta",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "09/05/2026",
    "file": "09_05_2026",
    "day": "sabado",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "10/05/2026",
    "file": "10_05_2026",
    "day": "domingo",
    "week": 19,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "11/05/2026",
    "file": "11_05_2026",
    "day": "segunda",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "12/05/2026",
    "file": "12_05_2026",
    "day": "terca",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "13/05/2026",
    "file": "13_05_2026",
    "day": "quarta",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "14/05/2026",
    "file": "14_05_2026",
    "day": "quinta",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "15/05/2026",
    "file": "15_05_2026",
    "day": "sexta",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "16/05/2026",
    "file": "16_05_2026",
    "day": "sabado",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "17/05/2026",
    "file": "17_05_2026",
    "day": "domingo",
    "week": 20,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "18/05/2026",
    "file": "18_05_2026",
    "day": "segunda",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "19/05/2026",
    "file": "19_05_2026",
    "day": "terca",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "20/05/2026",
    "file": "20_05_2026",
    "day": "quarta",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "21/05/2026",
    "file": "21_05_2026",
    "day": "quinta",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "22/05/2026",
    "file": "22_05_2026",
    "day": "sexta",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "23/05/2026",
    "file": "23_05_2026",
    "day": "sabado",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "24/05/2026",
    "file": "24_05_2026",
    "day": "domingo",
    "week": 21,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "25/05/2026",
    "file": "25_05_2026",
    "day": "segunda",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Registrar 5 erros e 5 acertos-chave",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "26/05/2026",
    "file": "26_05_2026",
    "day": "terca",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "1 pagina de revisao ativa",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "27/05/2026",
    "file": "27_05_2026",
    "day": "quarta",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Atualizar caderno de erros",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "28/05/2026",
    "file": "28_05_2026",
    "day": "quinta",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Revisar formulas e unidades",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "29/05/2026",
    "file": "29_05_2026",
    "day": "sexta",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Revisao da semana inteira",
    "b2": "Mini simulado misto 15 questoes",
    "b3": "Corrigir tudo no mesmo dia",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "30/05/2026",
    "file": "30_05_2026",
    "day": "sabado",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Lista mista 25 questoes",
    "b2": "Correcao comentada + caderno de erros",
    "b3": "Separar 3 pontos fracos para a semana seguinte",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "31/05/2026",
    "file": "31_05_2026",
    "day": "domingo",
    "week": 22,
    "phase": "fase 1 | base forte",
    "b1": "Revisao leve",
    "b2": "Leitura de 1 texto + 5 questoes de interpreta",
    "b3": "Descanso ativo, sem carga pesada",
    "goal": "construir base sem atropelo"
  },
  {
    "date": "01/06/2026",
    "file": "01_06_2026",
    "day": "segunda",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "02/06/2026",
    "file": "02_06_2026",
    "day": "terca",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "03/06/2026",
    "file": "03_06_2026",
    "day": "quarta",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "04/06/2026",
    "file": "04_06_2026",
    "day": "quinta",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "05/06/2026",
    "file": "05_06_2026",
    "day": "sexta",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "06/06/2026",
    "file": "06_06_2026",
    "day": "sabado",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "07/06/2026",
    "file": "07_06_2026",
    "day": "domingo",
    "week": 23,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "08/06/2026",
    "file": "08_06_2026",
    "day": "segunda",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "09/06/2026",
    "file": "09_06_2026",
    "day": "terca",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "10/06/2026",
    "file": "10_06_2026",
    "day": "quarta",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "11/06/2026",
    "file": "11_06_2026",
    "day": "quinta",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "12/06/2026",
    "file": "12_06_2026",
    "day": "sexta",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "13/06/2026",
    "file": "13_06_2026",
    "day": "sabado",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "14/06/2026",
    "file": "14_06_2026",
    "day": "domingo",
    "week": 24,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "15/06/2026",
    "file": "15_06_2026",
    "day": "segunda",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "16/06/2026",
    "file": "16_06_2026",
    "day": "terca",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "17/06/2026",
    "file": "17_06_2026",
    "day": "quarta",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "18/06/2026",
    "file": "18_06_2026",
    "day": "quinta",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "19/06/2026",
    "file": "19_06_2026",
    "day": "sexta",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "20/06/2026",
    "file": "20_06_2026",
    "day": "sabado",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "21/06/2026",
    "file": "21_06_2026",
    "day": "domingo",
    "week": 25,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "22/06/2026",
    "file": "22_06_2026",
    "day": "segunda",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "23/06/2026",
    "file": "23_06_2026",
    "day": "terca",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "24/06/2026",
    "file": "24_06_2026",
    "day": "quarta",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "25/06/2026",
    "file": "25_06_2026",
    "day": "quinta",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "26/06/2026",
    "file": "26_06_2026",
    "day": "sexta",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "27/06/2026",
    "file": "27_06_2026",
    "day": "sabado",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "28/06/2026",
    "file": "28_06_2026",
    "day": "domingo",
    "week": 26,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "29/06/2026",
    "file": "29_06_2026",
    "day": "segunda",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "30/06/2026",
    "file": "30_06_2026",
    "day": "terca",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "01/07/2026",
    "file": "01_07_2026",
    "day": "quarta",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "02/07/2026",
    "file": "02_07_2026",
    "day": "quinta",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "03/07/2026",
    "file": "03_07_2026",
    "day": "sexta",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "04/07/2026",
    "file": "04_07_2026",
    "day": "sabado",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "05/07/2026",
    "file": "05_07_2026",
    "day": "domingo",
    "week": 27,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "06/07/2026",
    "file": "06_07_2026",
    "day": "segunda",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "07/07/2026",
    "file": "07_07_2026",
    "day": "terca",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "08/07/2026",
    "file": "08_07_2026",
    "day": "quarta",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "09/07/2026",
    "file": "09_07_2026",
    "day": "quinta",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "10/07/2026",
    "file": "10_07_2026",
    "day": "sexta",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "11/07/2026",
    "file": "11_07_2026",
    "day": "sabado",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "12/07/2026",
    "file": "12_07_2026",
    "day": "domingo",
    "week": 28,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "13/07/2026",
    "file": "13_07_2026",
    "day": "segunda",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "14/07/2026",
    "file": "14_07_2026",
    "day": "terca",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "15/07/2026",
    "file": "15_07_2026",
    "day": "quarta",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "16/07/2026",
    "file": "16_07_2026",
    "day": "quinta",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "17/07/2026",
    "file": "17_07_2026",
    "day": "sexta",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "18/07/2026",
    "file": "18_07_2026",
    "day": "sabado",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "19/07/2026",
    "file": "19_07_2026",
    "day": "domingo",
    "week": 29,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "20/07/2026",
    "file": "20_07_2026",
    "day": "segunda",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "21/07/2026",
    "file": "21_07_2026",
    "day": "terca",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "22/07/2026",
    "file": "22_07_2026",
    "day": "quarta",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "23/07/2026",
    "file": "23_07_2026",
    "day": "quinta",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "24/07/2026",
    "file": "24_07_2026",
    "day": "sexta",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "25/07/2026",
    "file": "25_07_2026",
    "day": "sabado",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Simulado parcial 30 questoes",
    "b2": "Correcao e ranking dos top 5 erros",
    "b3": "Montar lista de retomada para domingo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "26/07/2026",
    "file": "26_07_2026",
    "day": "domingo",
    "week": 30,
    "phase": "fase 2 | consolidacao",
    "b1": "Retomada dos 5 erros da semana",
    "b2": "Flashcards + leitura de apoio leve",
    "b3": "Descanso ativo",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "27/07/2026",
    "file": "27_07_2026",
    "day": "segunda",
    "week": 31,
    "phase": "fase 2 | consolidacao",
    "b1": "Portugues",
    "b2": "Matematica",
    "b3": "Corrigir com foco em padrao de erro",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "28/07/2026",
    "file": "28_07_2026",
    "day": "terca",
    "week": 31,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica aplicada",
    "b3": "Anotar formulas e conceitos travados",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "29/07/2026",
    "file": "29_07_2026",
    "day": "quarta",
    "week": 31,
    "phase": "fase 2 | consolidacao",
    "b1": "Humanas",
    "b2": "Portugues",
    "b3": "Revisao rapida dos erros da segunda",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "30/07/2026",
    "file": "30_07_2026",
    "day": "quinta",
    "week": 31,
    "phase": "fase 2 | consolidacao",
    "b1": "Ciencias",
    "b2": "Matematica",
    "b3": "Fechar o dia com revisao ativa de 20 min",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "31/07/2026",
    "file": "31_07_2026",
    "day": "sexta",
    "week": 31,
    "phase": "fase 2 | consolidacao",
    "b1": "Mini simulado misto 20 questoes",
    "b2": "Correcao detalhada",
    "b3": "Classificar erros: conteudo, pressa ou interpretac",
    "goal": "terminar teoria e ganhar ritmo"
  },
  {
    "date": "01/08/2026",
    "file": "01_08_2026",
    "day": "sabado",
    "week": 31,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 50 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "02/08/2026",
    "file": "02_08_2026",
    "day": "domingo",
    "week": 31,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "03/08/2026",
    "file": "03_08_2026",
    "day": "segunda",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "04/08/2026",
    "file": "04_08_2026",
    "day": "terca",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "05/08/2026",
    "file": "05_08_2026",
    "day": "quarta",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "06/08/2026",
    "file": "06_08_2026",
    "day": "quinta",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "07/08/2026",
    "file": "07_08_2026",
    "day": "sexta",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "08/08/2026",
    "file": "08_08_2026",
    "day": "sabado",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 40 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "09/08/2026",
    "file": "09_08_2026",
    "day": "domingo",
    "week": 32,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "10/08/2026",
    "file": "10_08_2026",
    "day": "segunda",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "11/08/2026",
    "file": "11_08_2026",
    "day": "terca",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "12/08/2026",
    "file": "12_08_2026",
    "day": "quarta",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "13/08/2026",
    "file": "13_08_2026",
    "day": "quinta",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "14/08/2026",
    "file": "14_08_2026",
    "day": "sexta",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "15/08/2026",
    "file": "15_08_2026",
    "day": "sabado",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 50 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "16/08/2026",
    "file": "16_08_2026",
    "day": "domingo",
    "week": 33,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "17/08/2026",
    "file": "17_08_2026",
    "day": "segunda",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "18/08/2026",
    "file": "18_08_2026",
    "day": "terca",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "19/08/2026",
    "file": "19_08_2026",
    "day": "quarta",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "20/08/2026",
    "file": "20_08_2026",
    "day": "quinta",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "21/08/2026",
    "file": "21_08_2026",
    "day": "sexta",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "22/08/2026",
    "file": "22_08_2026",
    "day": "sabado",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 40 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "23/08/2026",
    "file": "23_08_2026",
    "day": "domingo",
    "week": 34,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "24/08/2026",
    "file": "24_08_2026",
    "day": "segunda",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "25/08/2026",
    "file": "25_08_2026",
    "day": "terca",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "26/08/2026",
    "file": "26_08_2026",
    "day": "quarta",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "27/08/2026",
    "file": "27_08_2026",
    "day": "quinta",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "28/08/2026",
    "file": "28_08_2026",
    "day": "sexta",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "29/08/2026",
    "file": "29_08_2026",
    "day": "sabado",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 50 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "30/08/2026",
    "file": "30_08_2026",
    "day": "domingo",
    "week": 35,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "31/08/2026",
    "file": "31_08_2026",
    "day": "segunda",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "01/09/2026",
    "file": "01_09_2026",
    "day": "terca",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "02/09/2026",
    "file": "02_09_2026",
    "day": "quarta",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "03/09/2026",
    "file": "03_09_2026",
    "day": "quinta",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "04/09/2026",
    "file": "04_09_2026",
    "day": "sexta",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "05/09/2026",
    "file": "05_09_2026",
    "day": "sabado",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 40 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "06/09/2026",
    "file": "06_09_2026",
    "day": "domingo",
    "week": 36,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "07/09/2026",
    "file": "07_09_2026",
    "day": "segunda",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "08/09/2026",
    "file": "08_09_2026",
    "day": "terca",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "09/09/2026",
    "file": "09_09_2026",
    "day": "quarta",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "10/09/2026",
    "file": "10_09_2026",
    "day": "quinta",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "11/09/2026",
    "file": "11_09_2026",
    "day": "sexta",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "12/09/2026",
    "file": "12_09_2026",
    "day": "sabado",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 50 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "13/09/2026",
    "file": "13_09_2026",
    "day": "domingo",
    "week": 37,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "14/09/2026",
    "file": "14_09_2026",
    "day": "segunda",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "15/09/2026",
    "file": "15_09_2026",
    "day": "terca",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "16/09/2026",
    "file": "16_09_2026",
    "day": "quarta",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "17/09/2026",
    "file": "17_09_2026",
    "day": "quinta",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "18/09/2026",
    "file": "18_09_2026",
    "day": "sexta",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "19/09/2026",
    "file": "19_09_2026",
    "day": "sabado",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 40 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "20/09/2026",
    "file": "20_09_2026",
    "day": "domingo",
    "week": 38,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "21/09/2026",
    "file": "21_09_2026",
    "day": "segunda",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "22/09/2026",
    "file": "22_09_2026",
    "day": "terca",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "23/09/2026",
    "file": "23_09_2026",
    "day": "quarta",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "24/09/2026",
    "file": "24_09_2026",
    "day": "quinta",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Natureza + Humanas",
    "b2": "15 questoes mistas",
    "b3": "Atualizar mapa de fraquezas",
    "goal": "resolver prova como prova"
  },
  {
    "date": "25/09/2026",
    "file": "25_09_2026",
    "day": "sexta",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Mini simulado 25 questoes",
    "b2": "Correcao completa",
    "b3": "Escolher 2 materias para reforco no sabado",
    "goal": "resolver prova como prova"
  },
  {
    "date": "26/09/2026",
    "file": "26_09_2026",
    "day": "sabado",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Simulado misto 50 questoes",
    "b2": "Correcao por bloco",
    "b3": "Marcar tempo gasto por materia",
    "goal": "resolver prova como prova"
  },
  {
    "date": "27/09/2026",
    "file": "27_09_2026",
    "day": "domingo",
    "week": 39,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Correcao final do simulado",
    "b2": "Revisao dos erros + flashcards",
    "b3": "Carga leve",
    "goal": "resolver prova como prova"
  },
  {
    "date": "28/09/2026",
    "file": "28_09_2026",
    "day": "segunda",
    "week": 40,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "20 questoes mistas cronometradas",
    "b3": "Caderno de erros obrigatorio",
    "goal": "resolver prova como prova"
  },
  {
    "date": "29/09/2026",
    "file": "29_09_2026",
    "day": "terca",
    "week": 40,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Bloco interdisciplinar",
    "b2": "15 questoes + correcao imediata",
    "b3": "Revisar conceitos travados",
    "goal": "resolver prova como prova"
  },
  {
    "date": "30/09/2026",
    "file": "30_09_2026",
    "day": "quarta",
    "week": 40,
    "phase": "fase 3 | treino interdisciplinar",
    "b1": "Matematica de prova",
    "b2": "Portugues de prova",
    "b3": "Comparar desempenho com semana anterior",
    "goal": "resolver prova como prova"
  },
  {
    "date": "01/10/2026",
    "file": "01_10_2026",
    "day": "quinta",
    "week": 40,
    "phase": "fase 4 | reta final",
    "b1": "Simulado parcial 25 questoes",
    "b2": "Correcao completa",
    "b3": "Separar o que ainda derruba desempenho",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "02/10/2026",
    "file": "02_10_2026",
    "day": "sexta",
    "week": 40,
    "phase": "fase 4 | reta final",
    "b1": "Revisao geral da semana",
    "b2": "Mini lista de reparo 10-12 questoes",
    "b3": "Fechar sem pendencias",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "03/10/2026",
    "file": "03_10_2026",
    "day": "sabado",
    "week": 40,
    "phase": "fase 4 | reta final",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao por materia",
    "b3": "Registrar nota e tempo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "04/10/2026",
    "file": "04_10_2026",
    "day": "domingo",
    "week": 40,
    "phase": "fase 4 | reta final",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e formulas",
    "b3": "Descanso ativo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "05/10/2026",
    "file": "05_10_2026",
    "day": "segunda",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Portugues + Matematica nos erros a",
    "b2": "20 questoes de reparo",
    "b3": "Meta: errar menos os assuntos repetidos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "06/10/2026",
    "file": "06_10_2026",
    "day": "terca",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Ciencias da Natureza",
    "b2": "15 questoes cronometradas",
    "b3": "Revisao ativa de formulas e conceitos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "07/10/2026",
    "file": "07_10_2026",
    "day": "quarta",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Humanas + interpretacao",
    "b2": "15 questoes",
    "b3": "Atualizar ranking de top 10 erros",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "08/10/2026",
    "file": "08_10_2026",
    "day": "quinta",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Simulado parcial 25 questoes",
    "b2": "Correcao completa",
    "b3": "Separar o que ainda derruba desempenho",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "09/10/2026",
    "file": "09_10_2026",
    "day": "sexta",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Revisao geral da semana",
    "b2": "Mini lista de reparo 10-12 questoes",
    "b3": "Fechar sem pendencias",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "10/10/2026",
    "file": "10_10_2026",
    "day": "sabado",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao por materia",
    "b3": "Registrar nota e tempo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "11/10/2026",
    "file": "11_10_2026",
    "day": "domingo",
    "week": 41,
    "phase": "fase 4 | reta final",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e formulas",
    "b3": "Descanso ativo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "12/10/2026",
    "file": "12_10_2026",
    "day": "segunda",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Portugues + Matematica nos erros a",
    "b2": "20 questoes de reparo",
    "b3": "Meta: errar menos os assuntos repetidos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "13/10/2026",
    "file": "13_10_2026",
    "day": "terca",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Ciencias da Natureza",
    "b2": "15 questoes cronometradas",
    "b3": "Revisao ativa de formulas e conceitos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "14/10/2026",
    "file": "14_10_2026",
    "day": "quarta",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Humanas + interpretacao",
    "b2": "15 questoes",
    "b3": "Atualizar ranking de top 10 erros",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "15/10/2026",
    "file": "15_10_2026",
    "day": "quinta",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Simulado parcial 25 questoes",
    "b2": "Correcao completa",
    "b3": "Separar o que ainda derruba desempenho",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "16/10/2026",
    "file": "16_10_2026",
    "day": "sexta",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Revisao geral da semana",
    "b2": "Mini lista de reparo 10-12 questoes",
    "b3": "Fechar sem pendencias",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "17/10/2026",
    "file": "17_10_2026",
    "day": "sabado",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao por materia",
    "b3": "Registrar nota e tempo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "18/10/2026",
    "file": "18_10_2026",
    "day": "domingo",
    "week": 42,
    "phase": "fase 4 | reta final",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e formulas",
    "b3": "Descanso ativo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "19/10/2026",
    "file": "19_10_2026",
    "day": "segunda",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Portugues + Matematica nos erros a",
    "b2": "20 questoes de reparo",
    "b3": "Meta: errar menos os assuntos repetidos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "20/10/2026",
    "file": "20_10_2026",
    "day": "terca",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Ciencias da Natureza",
    "b2": "15 questoes cronometradas",
    "b3": "Revisao ativa de formulas e conceitos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "21/10/2026",
    "file": "21_10_2026",
    "day": "quarta",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Humanas + interpretacao",
    "b2": "15 questoes",
    "b3": "Atualizar ranking de top 10 erros",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "22/10/2026",
    "file": "22_10_2026",
    "day": "quinta",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Simulado parcial 25 questoes",
    "b2": "Correcao completa",
    "b3": "Separar o que ainda derruba desempenho",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "23/10/2026",
    "file": "23_10_2026",
    "day": "sexta",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Revisao geral da semana",
    "b2": "Mini lista de reparo 10-12 questoes",
    "b3": "Fechar sem pendencias",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "24/10/2026",
    "file": "24_10_2026",
    "day": "sabado",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao por materia",
    "b3": "Registrar nota e tempo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "25/10/2026",
    "file": "25_10_2026",
    "day": "domingo",
    "week": 43,
    "phase": "fase 4 | reta final",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e formulas",
    "b3": "Descanso ativo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "26/10/2026",
    "file": "26_10_2026",
    "day": "segunda",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Portugues + Matematica nos erros a",
    "b2": "20 questoes de reparo",
    "b3": "Meta: errar menos os assuntos repetidos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "27/10/2026",
    "file": "27_10_2026",
    "day": "terca",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Ciencias da Natureza",
    "b2": "15 questoes cronometradas",
    "b3": "Revisao ativa de formulas e conceitos",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "28/10/2026",
    "file": "28_10_2026",
    "day": "quarta",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Reforco de Humanas + interpretacao",
    "b2": "15 questoes",
    "b3": "Atualizar ranking de top 10 erros",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "29/10/2026",
    "file": "29_10_2026",
    "day": "quinta",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Simulado parcial 25 questoes",
    "b2": "Correcao completa",
    "b3": "Separar o que ainda derruba desempenho",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "30/10/2026",
    "file": "30_10_2026",
    "day": "sexta",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Revisao geral da semana",
    "b2": "Mini lista de reparo 10-12 questoes",
    "b3": "Fechar sem pendencias",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "31/10/2026",
    "file": "31_10_2026",
    "day": "sabado",
    "week": 44,
    "phase": "fase 4 | reta final",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao por materia",
    "b3": "Registrar nota e tempo",
    "goal": "corrigir fraquezas e estabilizar nota"
  },
  {
    "date": "01/11/2026",
    "file": "01_11_2026",
    "day": "domingo",
    "week": 44,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e leitura curta",
    "b3": "Recuperacao mental",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "02/11/2026",
    "file": "02_11_2026",
    "day": "segunda",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Revisao cirurgica",
    "b2": "Lista curta 12-15 questoes",
    "b3": "Foco em confianca e constancia",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "03/11/2026",
    "file": "03_11_2026",
    "day": "terca",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao essencial",
    "b3": "Nao emendar com estudo pesado",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "04/11/2026",
    "file": "04_11_2026",
    "day": "quarta",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Reparo dos erros do simulado de terca",
    "b2": "Revisao ativa + 8-10 questoes",
    "b3": "Zerar os erros repetidos",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "05/11/2026",
    "file": "05_11_2026",
    "day": "quinta",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Natureza + Humanas",
    "b2": "Lista mista 12 questoes",
    "b3": "Manter ritmo sem esgotar",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "06/11/2026",
    "file": "06_11_2026",
    "day": "sexta",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Mini simulado 20 questoes",
    "b2": "Correcao rapida",
    "b3": "Dormir cedo",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "07/11/2026",
    "file": "07_11_2026",
    "day": "sabado",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao curta e objetiva",
    "b3": "Apenas anotar o essencial",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "08/11/2026",
    "file": "08_11_2026",
    "day": "domingo",
    "week": 45,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e leitura curta",
    "b3": "Recuperacao mental",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "09/11/2026",
    "file": "09_11_2026",
    "day": "segunda",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Revisao cirurgica",
    "b2": "Lista curta 12-15 questoes",
    "b3": "Foco em confianca e constancia",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "10/11/2026",
    "file": "10_11_2026",
    "day": "terca",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao essencial",
    "b3": "Nao emendar com estudo pesado",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "11/11/2026",
    "file": "11_11_2026",
    "day": "quarta",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Reparo dos erros do simulado de terca",
    "b2": "Revisao ativa + 8-10 questoes",
    "b3": "Zerar os erros repetidos",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "12/11/2026",
    "file": "12_11_2026",
    "day": "quinta",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Natureza + Humanas",
    "b2": "Lista mista 12 questoes",
    "b3": "Manter ritmo sem esgotar",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "13/11/2026",
    "file": "13_11_2026",
    "day": "sexta",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Mini simulado 20 questoes",
    "b2": "Correcao rapida",
    "b3": "Dormir cedo",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "14/11/2026",
    "file": "14_11_2026",
    "day": "sabado",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao curta e objetiva",
    "b3": "Apenas anotar o essencial",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "15/11/2026",
    "file": "15_11_2026",
    "day": "domingo",
    "week": 46,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e leitura curta",
    "b3": "Recuperacao mental",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "16/11/2026",
    "file": "16_11_2026",
    "day": "segunda",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Revisao cirurgica",
    "b2": "Lista curta 12-15 questoes",
    "b3": "Foco em confianca e constancia",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "17/11/2026",
    "file": "17_11_2026",
    "day": "terca",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao essencial",
    "b3": "Nao emendar com estudo pesado",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "18/11/2026",
    "file": "18_11_2026",
    "day": "quarta",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Reparo dos erros do simulado de terca",
    "b2": "Revisao ativa + 8-10 questoes",
    "b3": "Zerar os erros repetidos",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "19/11/2026",
    "file": "19_11_2026",
    "day": "quinta",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Natureza + Humanas",
    "b2": "Lista mista 12 questoes",
    "b3": "Manter ritmo sem esgotar",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "20/11/2026",
    "file": "20_11_2026",
    "day": "sexta",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Mini simulado 20 questoes",
    "b2": "Correcao rapida",
    "b3": "Dormir cedo",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "21/11/2026",
    "file": "21_11_2026",
    "day": "sabado",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao curta e objetiva",
    "b3": "Apenas anotar o essencial",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "22/11/2026",
    "file": "22_11_2026",
    "day": "domingo",
    "week": 47,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Correcao do simulado + revisao leve",
    "b2": "Flashcards e leitura curta",
    "b3": "Recuperacao mental",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "23/11/2026",
    "file": "23_11_2026",
    "day": "segunda",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Revisao cirurgica",
    "b2": "Lista curta 12-15 questoes",
    "b3": "Foco em confianca e constancia",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "24/11/2026",
    "file": "24_11_2026",
    "day": "terca",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao essencial",
    "b3": "Nao emendar com estudo pesado",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "25/11/2026",
    "file": "25_11_2026",
    "day": "quarta",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Reparo dos erros do simulado de terca",
    "b2": "Revisao ativa + 8-10 questoes",
    "b3": "Zerar os erros repetidos",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "26/11/2026",
    "file": "26_11_2026",
    "day": "quinta",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Natureza + Humanas",
    "b2": "Lista mista 12 questoes",
    "b3": "Manter ritmo sem esgotar",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "27/11/2026",
    "file": "27_11_2026",
    "day": "sexta",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Mini simulado 20 questoes",
    "b2": "Correcao rapida",
    "b3": "Dormir cedo",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "28/11/2026",
    "file": "28_11_2026",
    "day": "sabado",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Simulado completo 50 questoes",
    "b2": "Correcao curta e objetiva",
    "b3": "Apenas anotar o essencial",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "29/11/2026",
    "file": "29_11_2026",
    "day": "domingo",
    "week": 48,
    "phase": "fase 5 | novembro decisivo",
    "b1": "Revisao leve",
    "b2": "Nada de carga pesada",
    "b3": "Preservar energia mental",
    "goal": "lapidar desempenho e chegar inteiro"
  },
  {
    "date": "30/11/2026",
    "file": "30_11_2026",
    "day": "segunda",
    "week": 49,
    "phase": "fase 5 | novembro decisivo",
    "b1": "dia da prova",
    "b2": "revisao ultra leve pela manha, se houver temp",
    "b3": "chegar descansado e administrar o tempo da prova",
    "goal": "execucao"
  }
];

const FASES = {
  'fase 1 | base forte':              { label: 'Fase 1 · Base Forte',            color: '#C0572A', bg: '#FDEEE8' },
  'fase 2 | consolidacao':            { label: 'Fase 2 · Consolidação',           color: '#2563EB', bg: '#EFF6FF' },
  'fase 3 | treino interdisciplinar': { label: 'Fase 3 · Treino Interdisciplinar',color: '#7C3AED', bg: '#F5F3FF' },
  'fase 4 | reta final':              { label: 'Fase 4 · Reta Final',             color: '#D97706', bg: '#FFFBEB' },
  'fase 5 | novembro decisivo':       { label: 'Fase 5 · Novembro Decisivo',      color: '#059669', bg: '#ECFDF5' }
};

const DIAS_PT = {
  segunda: 'Seg', terca: 'Ter', quarta: 'Qua',
  quinta:  'Qui', sexta: 'Sex', sabado: 'Sáb', domingo: 'Dom'
};
